In [1]:
# Run some setup code for this notebook.

import random
import numpy as np
from cs231n.data_utils import load_CIFAR10
import matplotlib.pyplot as plt

# This is a bit of magic to make matplotlib figures appear inline in the notebook
# rather than in a new window.
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2



# Load the raw CIFAR-10 data.
cifar10_dir = 'cs231n/datasets/cifar-10-batches-py'

# Cleaning up variables to prevent loading data multiple times (which may cause memory issue)
try:
   del X_train, y_train
   del X_test, y_test
   print('Clear previously loaded data.')
except:
   pass

X_train, y_train, X_test, y_test = load_CIFAR10(cifar10_dir)

# As a sanity check, we print out the size of the training and test data.
print('Training data shape: ', X_train.shape)
print('Training labels shape: ', y_train.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', y_test.shape)


# Subsample the data for more efficient code execution in this exercise
num_training = 5000
mask = list(range(num_training))
X_train = X_train[mask]
y_train = y_train[mask]

num_test = 500
mask = list(range(num_test))
X_test = X_test[mask]
y_test = y_test[mask]

# Reshape the image data into rows
X_train = np.reshape(X_train, (X_train.shape[0], -1))
X_test = np.reshape(X_test, (X_test.shape[0], -1))
print(X_train.shape, X_test.shape)

Training data shape:  (50000, 32, 32, 3)
Training labels shape:  (50000,)
Test data shape:  (10000, 32, 32, 3)
Test labels shape:  (10000,)
(5000, 3072) (500, 3072)


In [25]:
from cs231n.classifiers import KNearestNeighbor

# Create a kNN classifier instance. 
# Remember that training a kNN classifier is a noop: 
# the Classifier simply remembers the data and does no further processing 
classifier = KNearestNeighbor()
classifier.train(X_train, y_train)

In [27]:
num_folds = 5
k_choices = [1, 3, 5, 8, 10, 12, 15, 20, 50, 100]

X_train_folds = []
y_train_folds = []
################################################################################
# TODO:                                                                        #
# Split up the training data into folds. After splitting, X_train_folds and    #
# y_train_folds should each be lists of length num_folds, where                #
# y_train_folds[i] is the label vector for the points in X_train_folds[i].     #
# Hint: Look up the numpy array_split function.                                #
################################################################################
# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

X_train_folds = np.array_split(X_train, num_folds) 
y_train_folds = np.array_split(y_train, num_folds)
pass

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

# A dictionary holding the accuracies for different values of k that we find
# when running cross-validation. After running cross-validation,
# k_to_accuracies[k] should be a list of length num_folds giving the different
# accuracy values that we found when using that value of k.
k_to_accuracies = {}


################################################################################
# TODO:                                                                        #
# Perform k-fold cross validation to find the best value of k. For each        #
# possible value of k, run the k-nearest-neighbor algorithm num_folds times,   #
# where in each case you use all but one of the folds as training data and the #
# last fold as a validation set. Store the accuracies for all fold and all     #
# values of k in the k_to_accuracies dictionary.                               #
################################################################################
# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    
classifier = KNearestNeighbor()
# accuracies = np.zeros(num_folds)
# print(type(X_train_folds))
# print(len(X_train_folds))
# print(len(X_train_folds[0]))
# # print(X_train_folds)
# # print(X_train_folds.shape)
# temp_X = X_train_folds[:]
# # print(temp_X.shape)
# print(len(temp_X))
# print(len(temp_X[1]))
# X_validate_fold = temp_X.pop(2)
# print(len(X_validate_fold[0]))
# print(len(temp_X))
# print(len(temp_X[1]))
# print()
# [y for x in temp_X for y in x]
# temp_X = np.array([y for x in temp_X for y in x])
# print(len(temp_X))
# print(len(temp_X[1]))
# for k in k_choices:
#     accuracies = np.zeros(num_folds)
#     for fold in range(num_folds):
#         temp_X = X_train_folds[:]
#         temp_y = y_train_folds[:]
#         X_validate_fold = temp_X.pop(fold)
#         y_validate_fold = temp_y.pop(fold)

#         temp_X = np.array([y for x in temp_X for y in x])
#         temp_y = np.array([y for x in temp_y for y in x])
#         print(type(temp_X))
#         classifier.train(temp_X, temp_y)

#         y_test_pred = classifier.predict(X_validate_fold, k=k)
#         num_correct = np.sum(y_test_pred == y_validate_fold)
#         accuracy = float(num_correct) / len(y_validate_fold)
#         accuracies[fold] =accuracy
#     k_to_accuracies[k] = accuracies
# print(len(y_validate_fold))

X=[[1,2,3],[4,5,6]]
Y = np.array([x for x in X ])
print(Y)
print(type(Y))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [58]:
import time 
from PIL import Image
import numpy as np

start = time.time()
def get_mean_pixel(path):
    img = np.array(Image.open(path))
#     print(img.shape)# 1440,2560,4
    img_three = img[:,:,:3]
#     print(img_three.shape)# 1440,2560,3
    img_three = img_three.transpose(2,0,1)
#     print(img_three.shape)# 3,1440,2560
    mean_pixel= [0,0,0]
    for i in range(3):
        mean_pixel[i] = np.mean(img_three[i])    
    return mean_pixel 
# 图片路径
path = 'E:\\pycharm\\project\\assignment1\\image.png'
print(get_mean_pixel(path))
end = time.time()
print("Time : %fs" %(end - start))


[94.2745627170139, 79.67420301649305, 66.39199652777778]
Time : 0.159573s


In [88]:
import numpy as np
x =  np.array([[1,2,3],[4,5,6]])
y =  np.array([2,1,0])
# ind = np.zeros_like(x)
ind =x
print(ind)
print(ind[np.arange(1), y])
ind[np.arange(1), y] = 0
print(ind)
print(ind[np.arange(1), y])

[[1 2 3]
 [4 5 6]]
[3 2 1]
[[0 0 0]
 [4 5 6]]
[0 0 0]
